spring:
  profiles:
    active:
    - dev


---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: provide-data-8001 #入驻eureka的服务名称

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka



---
server:
  port: 8002

spring:
  profiles: test
  application:
    name: provide-data-8002 #入驻eureka的服务名称

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka